# Generated by Django 6.0.3 on 2026-04-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_forms', '0002_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='customer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
